### ISSUE TITLE
Adding multiple librarys to a function behavior does not work

### ISSUE THREAD

**Issue by MartinRenze** [MDE4CPP/MDE4CPP#25]
I tried to add multiple libraries separated by newline to a function behavior.
But it is interpreted as single library name and so breaks the make file. See screenshot below.

![error](https://user-images.githubusercontent.com/50701415/75080494-6de64f00-550c-11ea-965a-e305e03e7bf6.png)

This dirty workaround solved it for me:
1. Adding LIBRARY0 - LIBRARY3 to the function behavior language attribute.
2. Chaining the files content of MDE4CPP/generator/fUML4CPP/fUML4CPP.generator/src/fUML4CPP/generator/main/generateExecutionBuildFile.mtl to 
[content.txt](https://github.com/MDE4CPP/MDE4CPP/files/4238503/content.txt)

**Comment by AlexanderWichmann** [comment]
Hi, 

that's correct. So far, we have only supported one library in body entry.
Specifying libraries inside body is already a workaround. Better solution would be to use packageImport element. Unfortunately, this presupposes that there is a model from the library.
If no model is existing, you have to use the body entry. 

However, the UML4CPP generator has been updated so that multiple libraries can be specified in one body entry. (commited to development branch)
Line separator is used to separate library names. This should work for windows as well as for unix/ linux. (lineSeparator() operation is used, which should return the os specific string)

Best regards
